### PR TITLE
feat: follow pytest-html 4.0.0rc changes

### PR DESCRIPTION
**Pull request by NextAlone**
follows https://github.com/pytest-dev/pytest-html/tree/next-gen changes, which will be release soon i think

### CODE REVIEW

**Comment by Goraved** [comment]
Any updates on this one? Because with the `pytest-html==4.0.0` merger doesn't work correctly. It shows the correct number of tests, but the table contains only the results from the 1 report

**Comment by NextAlone** [comment]
> Any updates on this one? Because with the `pytest-html==4.0.0` merger doesn't work correctly. It shows the correct number of tests, but the table contains only the results from the 1 report

Ok I will take a look.

**Comment by akavbathen** [comment]
Hi

I will be adding support for pytest-html 4 this weekend. 

@NextAlone Ill take a look at what you did

**Comment by NextAlone** [comment]
> Hi
> 
> I will be adding support for pytest-html 4 this weekend. 
> 
> @NextAlone Ill take a look at what you did

Thank you for your attention and thank you for your work.

**Comment by NextAlone** [comment]
> Hi
> 
> I will be adding support for pytest-html 4 this weekend. 
> 
> @NextAlone Ill take a look at what you did

Thank you for your attention and thank you for your work.

**Comment by akavbathen** [comment]
released in 0.0.9

**Pull request closed without merging**
